---
- name: install packages for automate
  hosts: automate
  become: true
  roles:
    - jenkins

################ import_playbooks ######################

- name: Install Monitor packages
  import_playbook: 07_apt_install_packages_monitor.yml