---
- name: install packages common to all servers
  hosts: webservers
  become: true
  roles:
    - apache

################ import_playbooks ######################

- name: Deploy Apache Config to webservers
  import_playbook: 08_copy_config_webservers.yml