---
- name: publish website on webservers
  hosts: webserver01
  become: true

  tasks:

  - name: Install open-jdk
    apt:
      name: openjdk-11-jdk
      state: present

  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /home/ansible/iaac-gcloud/files/confluent_syslog
      state: directory
      recurse: yes
      owner: ansible
      group: ansible

# - name: download confluent syslog connector
#   ansible.builtin.get_url:
#     url: http://client.hub.confluent.io/confluent-hub-client-latest.tar.gz
#     dest: /home/ansible/iaac-gcloud/files/confluent_syslog/
#     mode: '0755'

  - name: extract syslog connector
    ansible.builtin.unarchive:
      src: http://client.hub.confluent.io/confluent-hub-client-latest.tar.gz
      dest: /home/ansible/iaac-gcloud/files/confluent_syslog/
      remote_src: yes
      owner: ansible
      group: ansible    

  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: /home/ansible/iaac-gcloud/files/confluent_set_path.sh
      dest: /home/ansible/iaac-gcloud/files/
      owner: ansible
      group: ansible
      mode: '0755'

  - name: execute shell script to export path 
    ansible.builtin.shell: /home/ansible/iaac-gcloud/files/confluent_set_path.sh