######################################################################
#       Create External IP's for servers
######################################################################
---
- name: create exterlal ip's
  hosts: localhost
  
  vars_files:
    - /home/ansible/iaac-gcloud/vars/vars_global.yml

  tasks:

    - name: create webserver01 external ip address
      gcp_compute_address:
        region: "{{ gcp_region }}"
        project: "{{ gcp_project }}"
        name: extip-webserver01
        address_type: external
        network_tier: "{{ gcp_net_tier }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_account_file }}"
        state: present
      register: network
    
    - name: create webserver02 external ip address
      gcp_compute_address:
        region: "{{ gcp_region }}"
        project: "{{ gcp_project }}"
        name: extip-webserver02
        address_type: external
        network_tier: "{{ gcp_net_tier }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_account_file }}"
        state: present
      register: network

    - name: create monitor external ip address
      gcp_compute_address:
        region: "{{ gcp_region }}"
        project: "{{ gcp_project }}"
        name: extip-monitor
        address_type: external
        network_tier: "{{ gcp_net_tier }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_account_file }}"

    - name: create automate external ip address
      gcp_compute_address:
        region: "{{ gcp_region }}"
        project: "{{ gcp_project }}"
        name: extip-automate
        address_type: external
        network_tier: "{{ gcp_net_tier }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_account_file }}"
#########################################################