---
- name: install packages common to all servers
  hosts: all
  become: true

  tasks:

############## installation tasks ##############################

    - name: install ufw
      apt:
        name: ufw
        state: present
    
    - name: install net-tools
      apt:
        name: net-tools
        state: present

    - name: install git
      apt:
        name: git
        state: present
