---
- name: install packages common to all servers
  hosts: webservers
  become: true

  tasks:

############## update all         ##############################

    - name: apt-get update on all hosts
      apt:
        update_cache: yes

############## installation tasks ##############################

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Enable service httpd, and not touch the state
      ansible.builtin.service:
        name: apache2
        enabled: yes

    - name: Start service httpd, if not started
      ansible.builtin.service:
        name: apache2
        state: started

############## Clean up tasks #################################

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

################ import_playbooks ######################

- name: Deploy Apache Config to webservers
  import_playbook: copy_config_webservers.yml