---
- name: Install GPG and keys
  hosts: monitor
  become: true

  tasks:

    - name: add Grafana Repository
      apt_repository:
        repo: "deb https://packages.grafana.com/enterprise/deb stable main"
        state: present
        validate_certs: no