---
- name: copy website01 config file webserver01
  hosts: test01
  become: true

  tasks:

    - name: copy website01 config file webserver01
      ansible.builtin.copy:
        src: /home/ansible/iaac-gcloud/files/website_config_test01
        dest: /etc/apache2/sites-available/
        owner: root
        group: root
        mode: '0644'
        backup: yes




- name: copy website02 config file webserver02
  hosts: test02
  become: true

  tasks:

    - name: copy website02 config file webserver02
      ansible.builtin.copy:
        src: /home/ansible/iaac-gcloud/files/website_config_test02
        dest: /etc/apache2/sites-available/
        owner: root
        group: root
        mode: '0644'
        backup: yes

