---
- name: copy website01 config file webserver01
  hosts: test01
  become: true

  tasks:

    - name: copy website01 config file webserver01
      ansible.builtin.copy:
        src: /home/ansible/iaac-gcloud/files/website_config_test01.conf
        dest: /etc/apache2/sites-available/website_config_test01.conf
        owner: root
        group: root
        mode: '0644'
        backup: yes

    - name: copy apache2.conf file to webserver01
      ansible.builtin.copy:
        src: /home/ansible/iaac-gcloud/files/apache2.conf
        dest: /etc/apache2/apache2.conf
        owner: root
        group: root
        mode: '0644'
        backup: yes

    - name: remove existing symlink for 000-default.conf file
      ansible.builtin.shell: rm /etc/apache2/sites-enabled/000-default.conf
      ignore_errors: yes

    - name: remove existing symlink for website_config_test01.conf file
      ansible.builtin.shell: rm /etc/apache2/sites-enabled/website_config_test01.conf
      ignore_errors: yes

    - name: create symlink for 000-default.conf file
      ansible.builtin.shell: ln /etc/apache2/sites-available/000-default.conf /etc/apache2/sites-enabled/000-default.conf

    - name: create symlink for website_config_test01.conf file
      ansible.builtin.shell: ln /etc/apache2/sites-available/website_config_test01.conf /etc/apache2/sites-enabled/website_config_test01.conf

    - name: stop Apache server
      ansible.builtin.shell: service apache2 stop

    - name: start Apache server
      ansible.builtin.shell: service apache2 start


############### Test02 Tasks ##########################################

- name: copy website02 config file webserver02
  hosts: test02
  become: true

  tasks:

    - name: copy website02 config file webserver02
      ansible.builtin.copy:
        src: /home/ansible/iaac-gcloud/files/website_config_test02.conf
        dest: /etc/apache2/sites-available/website_config_test02.conf
        owner: root
        group: root
        mode: '0644'
        backup: yes

    - name: copy apache2.conf file to webserver02
      ansible.builtin.copy:
        src: /home/ansible/iaac-gcloud/files/apache2.conf
        dest: /etc/apache2/apache2.conf
        owner: root
        group: root
        mode: '0644'
        backup: yes

    - name: remove existing symlink for 000-default.conf file
      ansible.builtin.shell: rm /etc/apache2/sites-enabled/000-default.conf
      ignore_errors: yes

    - name: remove existing symlink for website_config_test02.conf file
      ansible.builtin.shell: rm /etc/apache2/sites-enabled/website_config_test02.conf
      ignore_errors: yes

    - name: create symlink for 000-default.conf file
      ansible.builtin.shell: ln /etc/apache2/sites-available/000-default.conf /etc/apache2/sites-enabled/000-default.conf

    - name: create symlink for website_config_test02.conf file
      ansible.builtin.shell: ln /etc/apache2/sites-available/website_config_test02.conf /etc/apache2/sites-enabled/website_config_test02.conf

    - name: stop Apache server
      ansible.builtin.shell: service apache2 stop

    - name: start Apache server
      ansible.builtin.shell: service apache2 start
