- name: Create webserver02 gcp instance
  hosts: localhost
  
  vars_files:
    - /home/ansible/iaac-gcloud/vars/vars_global.yml
  
  tasks:
  
    - name: create webserver02 disk
      gcp_compute_disk:
        name: webserver02-disk
        size_gb: 10
        source_image: "{{ gcp_vm_img }}"
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_account_file }}"
        state: present
      register: disk

    - name: create a  VPC network
      gcp_compute_network:
        name: default
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_account_file }}"
        state: present
      register: network

    - name: create webserver02 public IP Address
      gcp_compute_address:
        name: extip-webserver02
        region: "{{ gcp_region }}"
        project: "{{ gcp_project }}"
        network_tier: "{{ gcp_net_tier }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_account_file }}"
        state: present
      register: address

    - name: create webserver02 instance
      gcp_compute_instance:
        name: webserver02
        machine_type: "{{ gcp_vm_type }}"
        disks:
        - auto_delete: 'true'
          boot: 'true'
          source: "{{ disk }}"
        network_interfaces:
        - network: "{{ network }}"
          access_configs:
          - name: External NAT
            network_tier: "{{ gcp_net_tier }}"
            nat_ip: "{{ address }}"
            type: ONE_TO_ONE_NAT
          network_ip: "10.172.0.20"
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        labels:
          all: dev
          webservers: prod
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_account_file }}"
        state: present
    - name: Show instance Details
      debug:
        msg: "The webserver02 instance is accessible at {{ address.address }}"