---
- name: Start all vm instances
  hosts: localhost
  
  vars_files:
    - /home/ansible/iaac-gcloud/vars/vars_global.yml
  
  tasks:

    - name: create a firewall
      gcp_compute_firewall:
        name: test_object
        allowed:
        - ip_protocol: tcp
          ports:
          - '23'
        target_tags:
        - test-ssh-server
        - staging-ssh-server
        source_tags:
        - test-ssh-clients
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_account_file }}"
        state: present