---

- name: Create gcp landing zone
  hosts: localhost
  
  vars:
    gcp_project: iaac-gloud-313808
    gcp_cred_kind: serviceaccount
    gcp_account_file: /home/frederic_pitteloud_gmail_com/security/ansible-iaac-gcloud.json
    gcp_zone: 'europe-west6-b'
    gcp_region: 'europe-west6'
    gcp_net_mgt: 'default'
    gcp_net_prod: 'iaac-gcloud-vpc'
    gcp_net_tier: 'standard'

  tasks:
###################################################################
#   - name: delete vpc network for servers
#     google.cloud.gcp_compute_network:
#       name: iaac-gloud-servers
#       auto_create_subnetworks: 'true'
#       project: "{{ gcp_project }}"
#       auth_kind: "{{ gcp_cred_kind }}"
#       service_account_file: "{{ gcp_account_file }}"
#       state: absent
#     register: network
    
#   - name: create vpc servers subnet
#     google.cloud.gcp_compute_subnetwork:
#       name: servers-subnet
#       region: "{{ gcp_region }}"
#       network: "{{ network }}"
#       ip_cidr_range: 10.172.0.10/24
#       project: "{{ gcp_project }}"
#       auth_kind: "{{ gcp_cred_kind }}"
#       service_account_file: "{{ gcp_account_file }}"
#       state: present
######################################################################
#       Create Internal IP's for servers
######################################################################

    - name: create webserver01 internal ip address
      google.cloud.gcp_compute_address:
        region: "{{ gcp_region }}"
        project: "{{ gcp_project }}"
        name: intip-webserver01
        address_type: internal
        address: 10.172.0.10
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_account_file }}"
        state: present
      register: network
    
    - name: create webserver02 internal ip address
      google.cloud.gcp_compute_address:
        region: "{{ gcp_region }}"
        project: "{{ gcp_project }}"
        name: intip-webserver02
        address_type: internal
        address: 10.172.0.20
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_account_file }}"
        state: present
      register: network
    
    - name: create monitor internal ip address
      google.cloud.gcp_compute_address:
        region: "{{ gcp_region }}"
        project: "{{ gcp_project }}"
        name: intip-monitor
        address_type: internal
        address: 10.172.0.30
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_account_file }}"
        state: present
      register: network

######################################################################
#       Create External IP's for servers
######################################################################

    - name: create monitor external ip address
      google.cloud.gcp_compute_address:
        region: "{{ gcp_region }}"
        project: "{{ gcp_project }}"
        name: extip-monitor
        address_type: external
        network_tier: "{{ gcp_net_tier }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_account_file }}"
        state: present
      register: network
