---
- name: Create webserver02 instance
  hosts: localhost
  
  vars_files:
    - /home/ansible/iaac-gcloud/vars/vars_global.yml

  vars:
    - network: {
               'selfLink': 'projects/iaac-333811/global/networks/default',
               'address' : "{{ gcp_webserver02_extip }}"
               }
  
  tasks:

    - name: Display network Dictionary 
      debug: var=network

    - name: Create webserver02 disk
      gcp_compute_disk:
        name: 'webserver02'
        size_gb: 10
        source_image: "{{ gcp_vm_img }}"
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_account_file }}"
        state: present
      register: disk

    - name: Create webserver02 instance
      gcp_compute_instance:
        name: 'webserver02'
        machine_type: "{{ gcp_vm_type_2 }}"
        disks:
        - auto_delete: 'true'
          boot: 'true'
          source: "{{ disk }}"
        network_interfaces:
        - network: "{{ network }}"
          access_configs:
          - name: External NAT
            type: ONE_TO_ONE_NAT
#           set_public_ptr: 'yes'
#           public_ptr_domain_name: "{{ gcp_pub_domain }}"
            network_tier: "{{ gcp_net_tier }}"
            nat_ip: "{{ network }}"
          network_ip: "{{ gcp_webserver02_intip }}"
        tags:
          items:
            - 'webserver02'
            - 'http-server'
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_account_file }}"
        state: present
        status: RUNNING

################ pause ######################

    - name: Pause for 30 seconds for instances start
      pause:
        seconds: 30

################ import_playbooks ######################

- name: Update instances and install packages
  import_playbook: apt_update_install_all.yml