---
- name: shutdown all vm instance
  hosts: localhost

  vars:
    gcp_project: iaac-333811
    gcp_cred_kind: serviceaccount
    gcp_account_file: /home/ansible/security/ansible-iaac-gcloud.json

  tasks:

    - name: shutdown automate vm instance
      gcp_compute_instance:
        name: automate
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_account_file }}"
        status: TERMINATED