---
- name: shutdown all vm instance
  hosts: localhost

  vars:
    gcp_project: iaac-333811
    gcp_cred_kind: serviceaccount
    gcp_account_file: /home/ansible/security/ansible-iaac-gcloud.json
    gcp_zone: 'europe-west6-b'
    gcp_region: 'europe-west6'

  tasks:

    - name: shutdown automate vm instance
      gcp_compute_instance:
        name: automate
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        region: "{{ gcp_region }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_account_file }}"
        status: TERMINATED