---
- name: install packages common to all servers
  hosts: automate
  become: true

  tasks:

############## update all         ##############################

    - name: apt-get update on all hosts
      apt:
        update_cache: yes

############## installation tasks ##############################

    - name: install open-jdk
      apt:
        name: openjdk-8-jre
        state: present

    - name: Add Jenkins signing key
      ansible.builtin.apt_key:
        url: http://pkg.jenkins-ci.org/debian-stable-rc/jenkins-ci.org.key
        state: present

    - name: Add Jenkins Repository
      ansible.builtin.apt_repository:
        repo: deb http://pkg.jenkins-ci.org/debian-stable-rc
        state: present

    - name: apt-get update on all hosts
      apt:
        update_cache: yes

    - name: Install jenkins
      apt:
        name: jenkins
        state: present

    - name: Enable service jenkins, and not touch the state
      ansible.builtin.service:
        name: jenkins
        enabled: yes

    - name: Start service jenkins, if not started
      ansible.builtin.service:
        name: jenkins
        state: started

############## Clean up tasks #################################

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

