---
- name: install packages common to all servers
  hosts: webservers
  become: true

  tasks:

############## update all         ##############################

    - name: apt-get update on all hosts
      apt:
        update_cache: yes

############## installation tasks ##############################

    - name: Install Apache
      apt:
        name: apache2
        state: present

############## Clean up tasks #################################

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

