- name: install webservers packages
  hosts: webservers
  become: true

  tasks:

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Install Git
      apt:
        name: git
        state: present