---
- name: Start all vm instances
  hosts: localhost
  
  vars_files:
    - /home/ansible/iaac-gcloud/vars/vars_global.yml
  
  tasks:

    - name: Start automate instance
      gcp_compute_instance:
        project: "{{ gcp_project }}"
        zone: "{{ gcp_zone }}"
        name: automate
        machine_type: "{{ gcp_vm_type }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_account_file }}"
        status: RUNNING

    - name: Start monitor instance
      gcp_compute_instance:
        project: "{{ gcp_project }}"
        zone: "{{ gcp_zone }}"
        name: monitor
        machine_type: "{{ gcp_vm_type }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_account_file }}"
        status: RUNNING

    - name: Start weberser01 instance
      gcp_compute_instance:
        project: "{{ gcp_project }}"
        zone: "{{ gcp_zone }}"
        name: webserver01
        machine_type: "{{ gcp_vm_type }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_account_file }}"
        status: RUNNING

    - name: Start webserver02 instance
      gcp_compute_instance:
        project: "{{ gcp_project }}"
        zone: "{{ gcp_zone }}"
        name: webserver02
        machine_type: "{{ gcp_vm_type }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_account_file }}"
        status: RUNNING

################ pause ######################

    - name: Pause for 30 seconds for instances start
      pause:
        seconds: 30

################ import_playbooks ######################

- name: install packages for all machines
  import_playbook: apt_update_install_all.yml