---
- name: Stop all vm instances
  hosts: localhost

  vars_files:
    - /home/ansible/iaac-gcloud/vars/vars_global.yml

  tasks:

    - name: Stop automate instance
      gcp_compute_instance:
        project: "{{ gcp_project }}"
        zone: "{{ gcp_zone }}"
        name: automate
        machine_type: "{{ gcp_vm_type }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_account_file }}"
        status: TERMINATED

    - name: Stop monitor instance
      gcp_compute_instance:
        project: "{{ gcp_project }}"
        zone: "{{ gcp_zone }}"
        name: monitor
        machine_type: "{{ gcp_vm_type }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_account_file }}"
        status: TERMINATED

    - name: Stop webserver01 instance
      gcp_compute_instance:
        project: "{{ gcp_project }}"
        zone: "{{ gcp_zone }}"
        name: webserver01
        machine_type: "{{ gcp_vm_type }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_account_file }}"
        status: TERMINATED

    - name: Stop webserver02 instance
      gcp_compute_instance:
        project: "{{ gcp_project }}"
        zone: "{{ gcp_zone }}"
        name: webserver02
        machine_type: "{{ gcp_vm_type }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_account_file }}"
        status: TERMINATED