---
- name: update all instances
  hosts: all
  become: true

  tasks:

    - name: apt-get update on all hosts
      apt:
        update_cache: yes
    
    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

    - name: moloch hosts file to all hosts
      ansible.builtin.copy:
        src: /etc/hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'
        backup: yes

#   - name: Upgrade the OS (apt-get dist-upgrade)
#     apt:
#       upgrade: dist
