---
- name: common varialbles
  hosts: localhost
  
  vars:
    gcp_project: iaac-gloud-313808
    gcp_cred_kind: serviceaccount
    gcp_account_file: /home/frederic_pitteloud_gmail_com/security/ansible-iaac-gcloud.json
    gcp_zone: 'europe-west6-b'
    gcp_region: 'europe-west6'
    gcp_net_mgt: 'default'
    gcp_vm_img: 'projects/ubuntu-os-cloud/global/images/ubuntu-2010-groovy-v20210511a'
    gcp_vm_type: 'e2-micro'
    gcp_net_tier: 'STANDARD'