---
- name: Create firewall rule test-ingress-23
  hosts: localhost
  
  vars_files:
    - /home/ansible/iaac-gcloud/vars/vars_global.yml
  
  vars:
    - 

  tasks:

    - name: firewall rule test-ingress-23
      gcp_compute_firewall:
        name: Create firewall rule test-ingress-23
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_account_file }}"
