############## install GIT ##################################

- name: install git
  apt:
    name: git

############## Add Ansible repo #######################

- name: Add ansible repository
  ansible.builtin.apt_repository:
    repo: 'ppa:ansible/ansible'
    codename: jammy

############## Install Ansible ##############################

- name: Install Ansible
  apt:
    name: ansible
    state: present

############## install default-jre ##############################

- name: Install default-jre
  apt:
    name: default-jre
    state: present

############## install default-jdk ##############################

- name: Install default-jdk
  apt:
    name: default-jdk
    state: present

############## install Jenkins #################################

- name: copy jenkins key to automate
  ansible.builtin.copy:
    src: /usr/share/keyrings/jenkins-keyring.asc
    dest: /usr/share/keyrings/jenkins-keyring.asc
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: copy source list to automate
  ansible.builtin.copy:
    src: /etc/apt/sources.list.d/jenkins.list
    dest: /etc/apt/sources.list.d/jenkins.list
    owner: root
    group: root
    mode: '0644'
    backup: yes

#- name: apt-get update on all hosts
#  apt:
#    update_cache: yes

- name: Install jenkins
  apt:
    name: jenkins
    state: present
    update_cache: yes

- name: Enable service jenkins, and not touch the state
  ansible.builtin.service:
    name: jenkins
    enabled: yes

####### Start Jenkins Service and pause #################

- name: Start service jenkins, if not started
  ansible.builtin.service:
   name: jenkins
   state: started

- name: Pause for 45 seconds for instances start
  pause:
   seconds: 45

################ Reboot the machine #####################

- name: reboot the machine
  ansible.builtin.reboot:

############## End ######################################