---
# tasks file for roles/prometheus

- name: update and install prometheus
  apt:
    name: prometheus
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: start prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes