---
# tasks file for roles/google
- name: Create automate disk
  gcp_compute_disk:
    name: 'automate'
    size_gb: 10
    source_image: "{{ gcp_vm_img }}"
    zone: "{{ gcp_zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_account_file }}"
    state: present
    register: disk

- name: Create automate instance
  gcp_compute_instance:
    name: 'automate'
    machine_type: "{{ gcp_vm_type_2 }}"
    disks:
    - auto_delete: 'true'
      boot: 'true'
      source: "{{ disk }}"
    network_interfaces:
    - network: "{{ network }}"
      access_configs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
        set_public_ptr: 'yes'
        network_tier: "{{ gcp_net_tier }}"
        nat_ip: "{{ network }}"
      network_ip: "{{ gcp_automate_intip }}"
    tags:
      items:
        - 'automate'
        - 'http-server'
    zone: "{{ gcp_zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_account_file }}"
    state: present
    status: RUNNING